# Generated by Django 4.1.3 on 2022-12-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_range_field', models.IntegerField()),
                ('range_field', models.IntegerField()),
                ('label_range_field', models.IntegerField()),
            ],
        ),
    ]
