# Generated by Django 4.1.3 on 2022-12-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0002_slidermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slidermodel',
            name='label_range_field',
        ),
        migrations.AddField(
            model_name='slidermodel',
            name='label_field',
            field=models.CharField(default=10, max_length=230),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slidermodel',
            name='name_range_field',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='slidermodel',
            name='range_field',
            field=models.CharField(max_length=200),
        ),
    ]
