# Generated by Django 4.1.3 on 2022-12-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0003_remove_slidermodel_label_range_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slidermodel',
            name='label_field',
        ),
        migrations.RemoveField(
            model_name='slidermodel',
            name='name_range_field',
        ),
        migrations.RemoveField(
            model_name='slidermodel',
            name='range_field',
        ),
        migrations.AddField(
            model_name='slidermodel',
            name='num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
