# Generated by Django 4.1.3 on 2022-12-21 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suggestions', '0004_remove_slidermodel_label_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionaryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_a_diet', models.BooleanField()),
                ('diet_meal_quantity', models.CharField(choices=[(1, 'always on diet'), (2, '1 time'), (3, '2 times'), (4, '3 times'), (5, '4 times'), (6, 'has no diet')], max_length=32)),
                ('phisical_exercises', models.CharField(choices=[(1, 'Yes, and more then 2 hours per week'), (2, 'Yes, but less then 2 hours per week'), (3, 'No, I do not do any phisical exercises')], max_length=32)),
                ('physical_activity', models.BooleanField()),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.DeleteModel(
            name='SliderModel',
        ),
        migrations.DeleteModel(
            name='Suggestion',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='CategoryQuestion',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
