# Generated by Django 4.1.3 on 2022-12-21 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0005_questionarymodel_remove_answer_question_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionaryModel',
        ),
    ]
