# Generated by Django 4.1.3 on 2022-12-21 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suggestions', '0006_delete_questionarymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionaryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_a_diet', models.BooleanField()),
                ('diet_meal_quantity', models.CharField(choices=[('ALWAYS', 'always on diet'), ('ONE', '1 time'), ('TWO', '2 times'), ('THREE', '3 times'), ('FOUR', '4 times'), ('NEVER', 'has no diet')], default=None, max_length=32)),
                ('phisical_exercises', models.CharField(choices=[('YES_MORE_2H', 'Yes, and more then 2 hours per week'), ('YES_LESS_2H', 'Yes, but less then 2 hours per week'), ('NO', 'No, I do not do any phisical exercises')], default=None, max_length=32)),
                ('physical_activity', models.BooleanField()),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
