# Generated by Django 4.1.3 on 2022-12-21 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0007_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionarymodel',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='questionarymodel',
            name='user',
        ),
    ]
