# Generated by Django 4.1.3 on 2022-12-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0008_remove_questionarymodel_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionarymodel',
            name='diet_meal_quantity',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='questionarymodel',
            name='phisical_exercises',
            field=models.CharField(max_length=32),
        ),
    ]
