# Generated by Django 4.1.3 on 2022-12-21 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0011_alter_questionarymodel_on_a_diet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionarymodel',
            name='diet_meal_quantity',
        ),
        migrations.RemoveField(
            model_name='questionarymodel',
            name='on_a_diet',
        ),
        migrations.RemoveField(
            model_name='questionarymodel',
            name='phisical_exercises',
        ),
        migrations.RemoveField(
            model_name='questionarymodel',
            name='physical_activity',
        ),
    ]
