# Generated by Django 4.1.3 on 2022-12-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0014_alter_questionarymodel_on_a_diet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionarymodel',
            name='on_a_diet',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default=None, max_length=3),
        ),
        migrations.AlterField(
            model_name='questionarymodel',
            name='physical_activity',
            field=models.BooleanField(choices=[('YES', 'YES'), ('NO', 'NO')], default=None, max_length=3),
        ),
    ]
