# Generated by Django 4.1.3 on 2022-12-21 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0016_alter_questionarymodel_physical_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionarymodel',
            name='on_a_diet',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default=None, max_length=3),
        ),
        migrations.AlterField(
            model_name='questionarymodel',
            name='physical_activity',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default=None, max_length=3),
        ),
    ]
