# Generated by Django 4.1.3 on 2022-12-21 23:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0017_alter_questionarymodel_on_a_diet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionarymodel',
            name='diet_meal_quantity',
        ),
        migrations.RemoveField(
            model_name='questionarymodel',
            name='on_a_diet',
        ),
        migrations.RemoveField(
            model_name='questionarymodel',
            name='phisical_exercises',
        ),
        migrations.RemoveField(
            model_name='questionarymodel',
            name='physical_activity',
        ),
        migrations.AddField(
            model_name='questionarymodel',
            name='day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='questionarymodel',
            name='gl_level',
            field=models.IntegerField(default=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionarymodel',
            name='weight',
            field=models.FloatField(default=90),
            preserve_default=False,
        ),
    ]
