# Generated by Django 4.1.3 on 2022-12-22 07:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0021_questionarymodel_diet_meal_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionarymodel',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
