# Generated by Django 4.1.3 on 2022-12-22 07:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0022_questionarymodel_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionarymodel',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
