# Generated by Django 4.1.3 on 2022-12-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0023_alter_questionarymodel_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_max', models.IntegerField(default=20)),
                ('points_achived', models.IntegerField(default=0)),
                ('forecast', models.CharField(default=None, max_length=32)),
                ('suggestion', models.CharField(default=None, max_length=32)),
            ],
        ),
    ]
