# Generated by Django 4.1.3 on 2022-12-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0030_alter_questionarymodel_phisical_exercises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionarymodel',
            name='diet_meal_quantity',
            field=models.CharField(choices=[('Always on diet', 'Always'), ('1 time', 'One Times'), ('2 times', 'Two Times'), ('3 times', 'Three Times'), ('4 times', 'Four Times'), ('I have no any diet', 'Never')], default='I have no any diet', max_length=256),
        ),
    ]
