# Generated by Django 4.1.3 on 2022-12-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0031_alter_questionarymodel_diet_meal_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionarymodel',
            name='phisical_exercises',
            field=models.CharField(choices=[('Yes, and more then 2 hours per week', 'Yes And More 2 Hours Per Week'), ('Yes, but less then 2 hours per week', 'Yes But Less 2 Hours Per Week'), ('No, I do not do any physical exercises', 'No')], default='No, I do not do any phisical exercises', max_length=256),
        ),
    ]
