# Generated by Django 4.1.3 on 2022-12-11 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthdata',
            name='user',
        ),
    ]
