# Generated by Django 4.1.3 on 2022-12-11 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_remove_healthdata_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthdata',
            name='daytime',
        ),
        migrations.AddField(
            model_name='healthdata',
            name='day',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
