# Generated by Django 4.1.3 on 2022-12-11 15:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_healthdata_daytime_healthdata_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthdata',
            name='user',
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
