# Generated by Django 4.1.3 on 2022-12-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_healthdata_user_alter_healthdata_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthdata',
            name='height',
            field=models.IntegerField(default=180),
            preserve_default=False,
        ),
    ]
