# Generated by Django 4.1.3 on 2022-12-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_healthdata_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdata',
            name='height',
            field=models.IntegerField(default=180),
        ),
    ]
