# Generated by Django 4.1.3 on 2022-12-11 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_healthdata_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthdata',
            name='height',
        ),
    ]
