# Generated by Django 4.1.3 on 2022-12-12 09:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_healthdata_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdata',
            name='day',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
