# Generated by Django 4.1.3 on 2022-12-15 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_healthdata_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthdata',
            options={'verbose_name_plural': 'Health Data'},
        ),
    ]
