# Generated by Django 4.1.3 on 2022-12-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_healthdata_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthdata',
            name='bmi',
            field=models.FloatField(default=18.5),
        ),
    ]
