# Generated by Django 4.1.3 on 2022-12-26 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_healthdata_bmi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthdata',
            name='bmi',
        ),
    ]
