# Generated by Django 4.1.3 on 2022-12-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='material',
            name='img',
            field=models.ImageField(default='diabetes.png', upload_to='card_images'),
        ),
    ]
