# Generated by Django 4.1.3 on 2022-12-09 10:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_rename_name_material_title_alter_material_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
