# Generated by Django 4.1.3 on 2023-01-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_remove_quiz_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time',
            field=models.IntegerField(default=5, help_text='duration of the quiz in minutes'),
            preserve_default=False,
        ),
    ]
