# Generated by Django 4.1.3 on 2022-12-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.IntegerField(default=180),
        ),
    ]
